seed_everything: 42

trainer:
  gpus: 1
  callbacks: null
  accumulate_grad_batches: null
  max_epochs: 10
  val_check_interval: 1000
  precision: 16
  num_sanity_val_steps: 2
  limit_val_batches: 2
  deterministic: false
  auto_lr_find: false
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        dirpath: checkpoints/
        filename: "{epoch:02d}-{gen_all_loss:.5f}"
        monitor: gen_all_loss
        mode: min
        save_top_k: -1
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: inpainting
      save_dir: lightning_logs/

model:
  gen_optimizer_lr: 0.0001
  dis_optimizer_lr: 0.0004

data:
  train_dataset:
    class_path: src.dataset.PlacesWithMask
    init_args:
      root: data/
      split: train
  train_batch_size: 16
  train_num_workers: 16

  val_dataset:
    class_path: src.dataset.PlacesWithMask
    init_args:
      root: data/
      split: val
  val_batch_size: 4
  val_num_workers: 16

